version: '3.2'
services:
  postgres:
    image: postgres:12.1
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    network_mode: micro

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local